PROJECT_NAME = task_5
CFLAGS = -Wall -Wextra -Werror -std=c11

all: $(PROJECT_NAME)_1_1 $(PROJECT_NAME)_1_2 $(PROJECT_NAME)_2_1 $(PROJECT_NAME)_2_2

$(PROJECT_NAME)_1_1:
	gcc $(PROJECT_NAME)_1_1.c -o $(PROJECT_NAME)_1_1.out

$(PROJECT_NAME)_1_2:
	gcc $(PROJECT_NAME)_1_2.c -o $(PROJECT_NAME)_1_2.out

$(PROJECT_NAME)_2_1:
	gcc $(PROJECT_NAME)_2_1.c -o $(PROJECT_NAME)_2_1.out

$(PROJECT_NAME)_2_2:
	gcc $(PROJECT_NAME)_2_2.c -o $(PROJECT_NAME)_2_2.out

clean:
	rm -rf *.out *.o *.a *.so *.out *.bin