PROJECT_NAME = task_3
CFLAGS = -Wall -Wextra -Werror -std=c11

$(PROJECT_NAME)_1_1:
	gcc $(PROJECT_NAME)_1_1.c -o $(PROJECT_NAME)_1_1.out
	./$(PROJECT_NAME)_1_1.out

$(PROJECT_NAME)_1_2:
	gcc $(PROJECT_NAME)_1_2.c -o $(PROJECT_NAME)_1_2.out
	./$(PROJECT_NAME)_1_2.out

$(PROJECT_NAME)_2_1:
	gcc $(PROJECT_NAME)_2_1.c -o $(PROJECT_NAME)_2_1.out
	./$(PROJECT_NAME)_2_1.out

$(PROJECT_NAME)_2_2:
	gcc $(PROJECT_NAME)_2_2.c -o $(PROJECT_NAME)_2_2.out
	./$(PROJECT_NAME)_2_2.out

$(PROJECT_NAME)_3_1:
	gcc $(PROJECT_NAME)_3_1.c -o $(PROJECT_NAME)_3_1.out
	./$(PROJECT_NAME)_3_1.out

$(PROJECT_NAME)_3_2:
	gcc $(PROJECT_NAME)_3_2.c -o $(PROJECT_NAME)_3_2.out
	./$(PROJECT_NAME)_3_2.out

$(PROJECT_NAME)_4_1:
	gcc $(PROJECT_NAME)_4_1.c -o $(PROJECT_NAME)_4_1.out
	./$(PROJECT_NAME)_4_1.out

$(PROJECT_NAME)_4_2:
	gcc $(PROJECT_NAME)_4_2.c -o $(PROJECT_NAME)_4_2.out
	./$(PROJECT_NAME)_4_2.out

clean:
	rm -rf *.out *.o *.a *.so *.out *.bin