PROJECT_NAME = task_4
CFLAGS = -Wall -Wextra -Werror -std=c11

$(PROJECT_NAME)_1_1:
	gcc $(PROJECT_NAME)_1_1.c -o $(PROJECT_NAME)_1_1.out
	./$(PROJECT_NAME)_1_1.out 5

$(PROJECT_NAME)_1_2:
	gcc $(PROJECT_NAME)_1_2.c -o $(PROJECT_NAME)_1_2.out
	./$(PROJECT_NAME)_1_2.out

$(PROJECT_NAME)_2:
	gcc $(PROJECT_NAME)_2.c -o $(PROJECT_NAME)_2.out
	./$(PROJECT_NAME)_2.out 10

$(PROJECT_NAME)_3:
	gcc $(PROJECT_NAME)_3.c -o $(PROJECT_NAME)_3.out
	./$(PROJECT_NAME)_3.out 10

$(PROJECT_NAME)_4_1:
	gcc $(PROJECT_NAME)_4_1.c -o $(PROJECT_NAME)_4_1.out
	./$(PROJECT_NAME)_4_1.out 5

$(PROJECT_NAME)_4_2:
	gcc $(PROJECT_NAME)_4_2.c -o $(PROJECT_NAME)_4_2.out
	./$(PROJECT_NAME)_4_2.out

$(PROJECT_NAME)_5:
	gcc $(PROJECT_NAME)_5.c -o $(PROJECT_NAME)_5.out
	./$(PROJECT_NAME)_5.out 10

$(PROJECT_NAME)_6:
	gcc $(PROJECT_NAME)_6.c -o $(PROJECT_NAME)_6.out
	./$(PROJECT_NAME)_6.out 10

$(PROJECT_NAME)_7:
	gcc $(PROJECT_NAME)_7.c -o $(PROJECT_NAME)_7.out
	./$(PROJECT_NAME)_7.out

$(PROJECT_NAME)_8:
	gcc $(PROJECT_NAME)_8.c -o $(PROJECT_NAME)_8.out
	./$(PROJECT_NAME)_8.out

$(PROJECT_NAME)_9:
	gcc $(PROJECT_NAME)_9.c -o $(PROJECT_NAME)_9.out
	./$(PROJECT_NAME)_9.out

$(PROJECT_NAME)_10:
	gcc $(PROJECT_NAME)_10.c -o $(PROJECT_NAME)_10.out
	./$(PROJECT_NAME)_10.out

clean:
	rm -rf *.out *.o *.a *.so *.out *.bin *.txt